version: '3.2'
services:
  # database
  friends-database:
    build: './images/database'
    restart: 'always'
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: "pg_isready -q -U postgres"
    ports:
      - "${DB_PORT_HOST}:5432"
    environment:
      - "LANG=ru_RU.UTF-8"
      - "FILLA_DB_USER=${DB_USER}"
      - "FILLA_DB_PASSWORD=${DB_PASSWORD}"
      - "FILLA_DB_DATABASE=${DB_DATABASE}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - ./volumes/database-volume:/var/lib/postgresql/data
  # friends list app
  friendslist-app:
    image: 'aegorova/friendslist'
    restart: on-failure
    environment:
      - "SERVER_PORT=8080"
      - "DATABASE_URL=jdbc:postgresql://friends-database:5432/${DB_DATABASE}"
      - "DATABASE_USERNAME=${DB_USER}"
      - "DATABASE_PASSWORD=${DB_PASSWORD}"
    ports:
      - "8080:8080"
    depends_on:
      - friends-database